draft: Payload fuzzer
Fraunhofer-AISEC/gallia pull request #154
Opened 2022-06-10 14:59 UTC by VeroSec

Added a scanner in which the payload of the service WriteDataByIdentifier can be fuzzed. 
It is possible to scan multiple services and data identifiers for the same ECU.
Additionally, an asynchronous task to observe specific CAN massages can serve as a feedback channel while fuzzing to look at possible message changes, that occurred because of the fuzzing process.

2022-06-13 07:27 UTC, rumpelsepp commented
I took the liberty and fixed all the ci-checks. The ci was mainly confused because of two problems which I fixed in master (8c0dd728a38fe766c5fc7e576becb53d1cf556f1, 382bd5e5baddeb867b90032eb359e543421dc1af).

Be careful to use unix fileendings instead of windows fileendings. There is a [git setting](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) that helps dealing with this problems automatically; I have this in my `~/.config/git/config` file:

```
[core]
	autocrlf = input
```

2022-06-15 13:14 UTC, rumpelsepp commented on src/gallia/udscan/scanner/fuzz_payloads.py
> +        self.can_recv_event.set()
The event is never read in the main loop, isn't it?

2022-06-15 13:17 UTC, rumpelsepp commented
Took the liberty to rebase against master und fix the linters. I also added @emedav as a Co-Author. Please pull with:

```
$ git pull --rebase
```

Is this ready to merge?

2022-06-27 15:15 UTC, VeroSec reviewed
reviewed and resolved all conversations

2022-06-27 15:15 UTC, VeroSec commented on src/gallia/udscan/scanner/fuzz_payloads.py
> +        self.can_recv_event.set()
The Event is not read, but it triggers a log message if the can reply changed.

2022-06-28 08:53 UTC, rumpelsepp commented on src/gallia/udscan/scanner/fuzz_payloads.py
> +        self.can_recv_event.set()
No, it doesn't. The event is not read. The log message is generated in a background task which is created in line 123. I suggest removing the event.

2022-06-28 08:55 UTC, rumpelsepp requested changes
Please remove the unused event. Otherwise looks good to me. I added the required Copyright and License tags. Now the CI runs.

2022-07-05 13:56 UTC, merged