Doip 2019
Fraunhofer-AISEC/gallia pull request #506
Opened 2024-02-15 16:17 UTC by peckto

Some changes to the DoIP Stack.
Still work in progress.
- [ ] fix TCP socket problem during discover with re-use port
- [ ] add support for DoIP version 2019

2024-02-16 08:33 UTC, rumpelsepp requested changes

2024-02-16 08:33 UTC, rumpelsepp commented on src/gallia/commands/discover/doip.py
> +                    f"[🫨] Got me some good errors when it should be working (dis an infinite loop): {repr(e)}"
```
{repr(e)} -> {e!r}
```

2024-02-16 08:33 UTC, rumpelsepp commented on src/gallia/transports/doip.py
> +            ProtocolVersion=ProtocolVersions.ISO_13400_2_2019,
Should this be configurable?

2024-02-16 08:33 UTC, rumpelsepp commented on src/gallia/transports/doip.py
> -            ProtocolVersion=ProtocolVersions.ISO_13400_2_2012,
Should this be configurable?

2024-02-16 08:33 UTC, rumpelsepp commented on src/gallia/transports/doip.py
> -            ProtocolVersion=ProtocolVersions.ISO_13400_2_2012,
Should this be configurable?

2024-02-16 08:33 UTC, rumpelsepp commented on src/gallia/transports/doip.py
> +    | DoIPNegativeAckResponse
Is the name of this reponse `DoiPNegativeAckResponse` or `NegativeAck` response? The naming is inconsistent. What does the standard say?

2024-02-16 08:33 UTC, rumpelsepp commented on src/gallia/transports/doip.py
> +    def unpack(cls, data: bytes) -> DoIPNegativeAckResponse:
we could return `typing.Self` here.

2024-02-28 14:33 UTC, ferdinandjarisch commented
I've moved my fixes regarding general DoIP discovery behavior and especially the issue with stalling scans to #510, since they are independent of the DoIP 2019 header.

After they have been reviewed and merged, this PR should be carefully rebased, such that only DoIP 2019-relevant parts of 445ab962d6e48b3fe57f129b8cdd88d9fafee026 remain.

I then have further comments about implementing support for the 2019 standard.

2024-04-03 20:52 UTC, ferdinandjarisch commented
Surpassed by #510

2024-04-03 20:52 UTC, closed without merging