docs: Improve documentation
Fraunhofer-AISEC/gallia pull request #51
Opened 2022-05-02 08:14 UTC by peckto

2022-05-02 08:19 UTC, peckto commented
Also solves #50

2022-05-04 14:04 UTC, rumpelsepp requested changes

2022-05-04 14:04 UTC, rumpelsepp commented on docs/internal.md
> +1. Scanner API (`gallia_scanner`)
We should rename this to `gallia_scanners`, since we use plural everywhere.

2022-05-05 06:12 UTC, rumpelsepp commented on docs/internal.md
> +1. Scanner API (`gallia_scanner`)
When we do this, remember to rename the entry point in `pyproject.toml` and `udscan.core` as well.

2022-05-05 06:27 UTC, rumpelsepp approved these changes

2022-05-05 06:44 UTC, merged