chore: Migrate to new context manager asyncio.timeou()
Fraunhofer-AISEC/gallia pull request #559
Opened 2024-07-18 13:25 UTC by rumpelsepp

2024-07-19 11:45 UTC, ferdinandjarisch commented
What exactly is the added benefit or the fixed bug of this change?

2024-07-19 11:52 UTC, ferdinandjarisch requested changes

2024-07-19 11:52 UTC, ferdinandjarisch commented on src/gallia/transports/doip.py
> +                            TimingAndCommunicationParameters.DiagnosticMessageMessageAckTimeout
We should avoid introducing new bugs, especially with such seemingly straightforward changes...

2024-07-21 16:17 UTC, rumpelsepp commented
> What exactly is the added benefit or the fixed bug of this change?

Code consistency. This is the recommended way of doing async timouts nowadays: https://docs.python.org/3/library/asyncio-task.html#timeouts.

I started to use this now API in #555 which would introduce a new way of doing things. For the sake of consistency I did this migration. IMO it is important to stay syncronized with how the community does things to keep the codebase evolving.

2025-10-17 07:59 UTC, closed without merging